version: "3.9"
services:

    nginx:
        container_name: music-nginx
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        container_name: music-php-fpm
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - .:/app
        networks:
            - app-network

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - .:/app

networks:
    app-network:
        driver: bridge
